xenstore: add xs access routines
xen-troops/zephyr-xenlib pull request #1
Opened 2023-02-20 10:00 UTC by sa-kib

Initial code for read & write to XS, also stub for permission setting.

2023-02-21 13:02 UTC, firscity commented on xenstore-srv/include/xss.h
> +#pragma once
Please add SPDX identifier and EPAM copyright.

2023-02-21 13:16 UTC, firscity requested changes
Please, also add why we need it in commit message.

2023-02-21 13:16 UTC, firscity commented on xenstore-srv/include/xss.h
> +int xss_read(const char *path, char *value, size_t len);
Please add functions description

2023-02-21 13:16 UTC, firscity commented on xenstore-srv/src/xenstore_srv.c
> +	k_mutex_lock(&xsel_mutex, K_FOREVER);
Please, add space after declaration.

2023-02-21 13:16 UTC, firscity commented on xenstore-srv/src/xenstore_srv.c
> +	if (!rc)
Please, add space after declaration.

2023-02-23 08:08 UTC, sa-kib commented on xenstore-srv/include/xss.h
> +#pragma once
added in 2e0617e

2023-02-23 08:09 UTC, sa-kib commented on xenstore-srv/include/xss.h
> +int xss_read(const char *path, char *value, size_t len);
added in 2e0617e

2023-02-23 08:09 UTC, sa-kib commented on xenstore-srv/src/xenstore_srv.c
> +	k_mutex_lock(&xsel_mutex, K_FOREVER);
added in 2e0617e

2023-02-23 08:09 UTC, sa-kib commented on xenstore-srv/src/xenstore_srv.c
> +	if (!rc)
added in 2e0617e

2023-02-23 08:09 UTC, sa-kib commented
> Please, also add why we need it in commit message.

commit msg updated

2023-02-23 10:06 UTC, firscity approved these changes
Please, add RB and force push squashed commit
`Reviewed-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2023-02-23 10:13 UTC, sa-kib commented
squashed & rebased

2023-02-23 10:14 UTC, merged