Various fixes for compiler warnings
xen-troops/zephyr-xenlib pull request #10
Opened 2023-03-08 19:41 UTC by firscity

2023-03-09 14:35 UTC, xakep-amatop requested changes

2023-03-09 14:38 UTC, xakep-amatop commented
review has been finished, 
I think that I have found a few minor issues and have one major question
pls, give me an answer to the major question

2023-03-09 15:12 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
>  			return iter;
Thanks, fixed.

2023-03-09 15:12 UTC, firscity commented on xenstore-srv/src/xenstore_srv.c
>  	size_t keyl = strlen(key);
Yes, it is called from exported functions (xss handlers). Check was added.

2023-03-09 15:12 UTC, firscity commented on xenstore-srv/src/xenstore_srv.c
> +	strncpy(key_buffer, key, keyl);
Fixed, thanks.

2023-03-09 15:13 UTC, firscity commented on xenstore-srv/src/xenstore_srv.c
> +void xs_evtchn_cb(void *priv);
Added TODO related to this declaration. It is caused by some unusual usage of evtchn cb and should be fixed.

2023-03-09 15:31 UTC, xakep-amatop approved these changes

2023-03-09 15:32 UTC, xakep-amatop commented
`Acked-by: Mykola Kvach <mykola_kvach@epam.com>`

2023-03-10 11:48 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-mgmt.c
>  {
Issue with locking here is deeper than just locking `&domain_list`.

As I see,  typical usage is something like this:

```
	domain = domid_to_domain(domid);
	if (!domain) {
		printk("No domain with domid = %u is present\n", domid);
```

Problem is that `domain` can be freed/destroyed right after `domid_to_domain()` return. You either need to refcount domains or to globally lock all domains state.

2023-03-10 15:11 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
>  {
Yes, I agree. Currently I replaced this changes in fixup with TODO, that contains problem description. I will analyze and fix it in separate PR. Thanks.

2023-03-14 11:57 UTC, LKomaryanskiy commented
@firscity Good job! LGTM +1, you can add
`Acked-by: Leonid Komarianskyi <leonid_komarianskyi@epam.com>`

2023-03-14 11:58 UTC, LKomaryanskiy approved these changes

2023-03-14 14:47 UTC, lorc commented
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2023-03-14 15:06 UTC, merged