Xrun implementation to zephyr-xenlib.
xen-troops/zephyr-xenlib pull request #16
Opened 2023-03-20 08:19 UTC by oleksiimoisieiev

Introducing xrun api to the zephyr xenlib. Xrun library allows application to provide bundle with runtime spec and start provided services as the Domains.

2023-03-20 08:49 UTC, xakep-amatop commented on xen-shell-cmd/CMakeLists.txt
> +zephyr_library_sources(src/xen_shell.c src/xen_cmds.c src/xrun_cmds.c)
(question) is it possible to build xen-shell without enabled `CONFIG_XRUN`?
if yes, should you add some checks here? I mean to add this file as a library source only in case when `CONFIG_XRUN` is enabled

2023-03-20 08:52 UTC, xakep-amatop commented on xrun/include/storage.h
> +					 size_t size);
(cosmetic) it isn't necessary to move this to another line, Zephyr allows maximum 100 symbols in one line

2023-03-20 08:52 UTC, xakep-amatop commented on xrun/include/storage.h
> +				  char *buf, size_t size, int skip);
(cosmetic) the same as above

2023-03-20 08:54 UTC, xakep-amatop commented on xen-shell-cmd/src/xrun_cmds.c
> +// SPDX-License-Identifier: Apache-2.0
(minor) pls, avoid using of one line comment style

2023-03-20 09:08 UTC, xakep-amatop commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	LOG_DBG("Zephyr Domain start addr = %p, binary size = 0x%llx\n",
(cosmetic) new line isn't needed, Logging subsystems add it automatically

2023-03-20 09:09 UTC, xakep-amatop commented on xen-dom-mgmt/src/xen-dom-mgmt.c
>  	if (!dtb_addr)
(major) looks like here we can have memory leak and few lines we below we also have return without memory free
```
if (mapped_domd == NULL)
		return 0;
```

2023-03-20 09:14 UTC, xakep-amatop commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	mapped_pfns = k_calloc(nr_pages, sizeof(xen_pfn_t));
(question) why can't you allocate one contiguous chunk of memory here instead of three calls? 
in this case:
* you can avoid calling so often alloc function
* you can avoid calling so often free function
* you will have less code inside this function

Are you afraid that we don't have one big non fragmented chunk of memory?

2023-03-20 09:16 UTC, Eabramov84 commented on xrun/include/xrun.h
> +int xrun_run(const char *bundle, int console_socket, const char *container_id);
Due to it is an interface please add comments and return value descriptions.

2023-03-20 09:34 UTC, xakep-amatop commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +		LOG_ERR("Image callback is not set\n");
(typo) callback**s**

2023-03-20 09:37 UTC, xakep-amatop commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +		LOG_ERR("Error calling load_image_bytes rc: %d\n", rc);
(cosmetic) new line isn't needed

2023-03-20 09:40 UTC, xakep-amatop commented on xen-shell-cmd/src/xrun_cmds.c
> +			pos++;
(question minor/major) is it possible that user after option enter a few spaces or tabs? should you handle it here?

2023-03-20 09:47 UTC, xakep-amatop commented on xen-shell-cmd/src/xrun_cmds.c
> +	return xrun_run(bundle, socket, container_id);
(question major) is it ok to have bundle equal to NULL?

2023-03-20 09:48 UTC, xakep-amatop commented on xen-shell-cmd/src/xrun_cmds.c
> +	socket = atoi(get_param(argc, argv, 's'));
(minor) I believe that you should perform checking of ret value from `atoi, an error can happen inside

2023-03-20 09:58 UTC, xakep-amatop commented on xen-shell-cmd/src/xrun_cmds.c
> +	if (argc < 5 || argc > 7) {
(question minor) why do you need this checks at all here and below functions?
you already provide an amount of mandatory options to cmd constructor:
```
/**
 * @brief Initializes a shell command with arguments.
 *
 * @note If a command will be called with wrong number of arguments shell will
 * print an error message and command handler will not be called.
 *
 * @param[in] syntax	 Command syntax (for example: history).
 * @param[in] subcmd	 Pointer to a subcommands array.
 * @param[in] help	 Pointer to a command help string.
 * @param[in] handler	 Pointer to a function handler.
 * @param[in] mand	 Number of mandatory arguments including command name.
 * @param[in] opt	 Number of optional arguments.
 */
#define SHELL_CMD_ARG(syntax, subcmd, help, handler, mand, opt) \
```

2023-03-20 09:59 UTC, oleksiimoisieiev commented on xen-shell-cmd/src/xrun_cmds.c
> +// SPDX-License-Identifier: Apache-2.0
This is the requirement of checkpatch. It requires different format of SPDX for *.c and *.h files.

2023-03-20 10:02 UTC, oleksiimoisieiev commented on xen-shell-cmd/src/xrun_cmds.c
> +			pos++;
This implementation doesn't care about command line format. So if user wants some special chars in command line - they should provide the following format: param="test" and make sure it will be accepted by json.

2023-03-20 10:05 UTC, oleksiimoisieiev commented on xrun/include/storage.h
> +					 size_t size);
checkpatch in zephyr allows only 80 and I've checked all of my patches. If it doesn't fit format - I would have got error.

2023-03-20 10:08 UTC, xakep-amatop commented on xen-shell-cmd/src/xrun_cmds.c
> +SHELL_CMD_ARG_REGISTER(xrun, &subcmd_xrun, "XRun commands", NULL, 2, 0);
(note) looks like we have to set mandatory number of args to 3 instead of 2
it should be min of mandatory from `subcmd_xrun` array

2023-03-20 10:09 UTC, xakep-amatop commented on xen-shell-cmd/src/xrun_cmds.c
> +					"Invalid containerid passed to resume cmd\n");
(cosmetic) something strange with formatting

2023-03-20 10:10 UTC, xakep-amatop commented on xrun/src/storage.c
> +// SPDX-License-Identifier: Apache-2.0
(cosmetic) pls, avoid using of one line comments here and in other files

2023-03-20 10:14 UTC, xakep-amatop commented on xen-shell-cmd/src/xrun_cmds.c
> +// SPDX-License-Identifier: Apache-2.0
it is strange because zephyr sources don't have such strange combination
are you tacking about checkpatch for which project Linux or Zephyr?

2023-03-20 10:16 UTC, xakep-amatop commented on xrun/src/storage.c
> +	snprintf(fname, MAX_PATH_LEN, "%s/%s", path, name);
(note) this function can return negative error value

2023-03-20 10:22 UTC, xakep-amatop commented on xrun/src/storage.c
> +	rc = fs_open(&file, fname, FS_O_CREATE | FS_O_RDWR);
(question) why isn't enough to use `FS_O_WRITE`?

2023-03-20 11:08 UTC, xakep-amatop commented on xrun/include/storage.h
> +					 size_t size);
maybe we use different checkpatch scripts, because for me 100 symbols work good

2023-03-20 11:52 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	if (!container)
(cosmetic) pls. use curly braces even for one line under loop/if statements it is a requirement from Zephyr Code Guidelines here and above

2023-03-20 12:01 UTC, xakep-amatop commented on xrun/src/xrun.c
> +		return bytes_read;
(question) should you unregister container in case of any error or only after domain_create?

2023-03-20 12:02 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	parse_config_json(config, bytes_read, &container->spec);
(minor) unhandled status

2023-03-20 14:29 UTC, oleksiimoisieiev commented on xen-shell-cmd/CMakeLists.txt
> +zephyr_library_sources(src/xen_shell.c src/xen_cmds.c src/xrun_cmds.c)
+

2023-03-20 14:30 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	LOG_DBG("Zephyr Domain start addr = %p, binary size = 0x%llx\n",
+

2023-03-20 14:33 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
>  	if (!dtb_addr)
fixed. thanks

2023-03-20 14:38 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +		LOG_ERR("Image callback is not set\n");
+

2023-03-21 17:23 UTC, oleksiimoisieiev commented on xrun/src/storage.c
> +	snprintf(fname, MAX_PATH_LEN, "%s/%s", path, name);
+

2023-03-21 17:24 UTC, oleksiimoisieiev commented on xrun/src/storage.c
> +	rc = fs_open(&file, fname, FS_O_CREATE | FS_O_RDWR);
What if file doesn't exists? this was taken from sample.

2023-03-22 14:19 UTC, firscity commented on xrun/src/xrun.c
> +	k_spinlock_key_t key;
I'm not sure if it is OK, to declare variables after function calls.

2023-03-22 14:19 UTC, firscity commented on xrun/src/xrun.c
> +	if (!image_info) {
Should we verify buf too?

2023-03-22 14:19 UTC, firscity commented on xrun/src/xrun.c
> +	domcfg->mem_kb = 4096;
Should all of these values be hardcoded here? Looks pretty strange

2023-03-22 14:19 UTC, firscity commented on xrun/src/xrun.c
> +#if defined(CONFIG_XENVM_USE_GIC_V3)
This config is related to Dom0 Zephyr, not to created domain. AFAIK, if HW runs on GICv3, created domain may use both GICv2/GICv3.

2023-03-22 14:19 UTC, firscity commented on xrun/src/xrun.c
> +	if (!container) {
Should we verify bundle too?

2023-03-22 14:19 UTC, firscity commented on xrun/src/xrun.c
> +		k_free(config);
it may be another label before `err` and be reused in next condition too

2023-03-22 14:19 UTC, firscity commented on xen-shell-cmd/src/xrun_cmds.c
> +	printf("%s state is %d\n", container_id, state);
I'm not sure about `printf()`, it probably should be `shell_print()` here.

2023-03-23 13:58 UTC, oleksiimoisieiev commented on xen-shell-cmd/src/xrun_cmds.c
> +					"Invalid containerid passed to resume cmd\n");
finally fixed

2023-03-23 13:58 UTC, oleksiimoisieiev commented on xen-shell-cmd/src/xrun_cmds.c
> +	if (!container_id) {
fixed

2023-03-23 13:58 UTC, oleksiimoisieiev commented on xen-shell-cmd/src/xrun_cmds.c
> +	printf("%s state is %d\n", container_id, state);
fixed

2023-03-23 13:58 UTC, oleksiimoisieiev commented on xrun/include/storage.h
> +int lsdir(const char *path);
fixed

2023-03-23 14:20 UTC, oleksiimoisieiev commented on xrun/src/storage.c
> +#define MAX_PATH_LEN 255
Yes. it was taken from lfs.h. Dropped this define and used LFS_NAME_MAX

2023-03-23 14:20 UTC, oleksiimoisieiev commented on xrun/src/storage.c
> +	ret = snprintf(fname, MAX_PATH_LEN, "%s/%s", path, name);
fixed

2023-03-23 14:20 UTC, oleksiimoisieiev commented on xrun/src/storage.c
> +	rc = snprintf(fname, MAX_PATH_LEN, "%s/%s", path, name);
+

2023-03-23 14:20 UTC, oleksiimoisieiev commented on xrun/src/storage.c
> +	rc = snprintf(fname, MAX_PATH_LEN, "%s/%s", path, name);
+

2023-03-24 08:40 UTC, firscity commented on xen-dom-mgmt/include/domain.h
> +typedef int (*load_image_bytes_t)(uint8_t *buf, size_t bufsize,
Please, add this commit as PR to zephyr-dom0-xt to keep Zephyr DomU runnable

2023-03-24 08:40 UTC, firscity commented on xrun/src/xrun.c
> +	int ret = json_obj_parse(json,
Still can see a problem

2023-03-24 09:21 UTC, xakep-amatop requested changes

2023-03-24 09:21 UTC, xakep-amatop commented on xrun/src/storage.c
> +		goto out;
(cosmetic) unnecessary `goto`

2023-03-24 09:21 UTC, xakep-amatop commented on xrun/src/storage.c
> +	__ASSERT(path != NULL && name != NULL, "Invalid input parameters");
(question) Do we really need to assert here and in line below?
why we can exit with error ? I thought that code should be reliable

2023-03-24 09:21 UTC, xakep-amatop commented on xrun/src/storage.c
> +	if (rc == 0 && dirent.type == FS_DIR_ENTRY_FILE && dirent.size == 0) {
(question) is it really impossible to have zero-length file?

2023-03-24 09:21 UTC, xakep-amatop commented on xrun/src/storage.c
> +			LOG_DBG("[DIR ] %s\n", entry.name);
(question) why do you always add extra new line ? `LOG_DBG` has already added one

2023-03-24 09:21 UTC, xakep-amatop commented on xrun/src/storage.c
> +	char fname[LFS_NAME_MAX];
LFS_NAME_MAX only applies to filenames. It mirrors the POSIX [NAME_MAX](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/limits.h.html) constant.

There is no limit on the path length other then the RAM and storage you have on your device. lfs_file_open makes sure to write the file name to disk and doesn't keep it around.

2023-03-24 09:21 UTC, xakep-amatop commented on xrun/src/storage.c
> +	rc = fs_open(&file, fname, FS_O_CREATE | FS_O_RDWR);
I have meant that READ flag is useless here, I haven't meant `FS_O_CREATE`...
pls, use `FS_O_WRITE` instead of `FS_O_RDWR`

2023-03-24 10:08 UTC, xakep-amatop requested changes

2023-03-24 10:08 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	bytes_read = read_file(bundle, "config.json", config,
(question) is it possible to get size of file and compare it with `CONFIG_XRUN_JSON_SIZE_MAX` here and print some warning at least?

2023-03-24 10:08 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	if (bytes_read < 0) {
(question) is it possible to have `bytes_read` is equal to `0` here?

2023-03-24 10:08 UTC, xakep-amatop commented on xrun/src/xrun.c
> +		LOG_ERR("Can't read config.json ret = %ld\n", bytes_read);
(cosmetic) pls, remove extra new lines in all files for all logs

2023-03-24 10:08 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	ret = snprintf(container->kernel_image,
(question) Could you please also add checking if we write less bytes than expected?
```
ret < strlen(spec.vm.kernel.path)
```

2023-03-24 10:08 UTC, xakep-amatop commented on xrun/src/xrun.c
> +					   "%s", spec.vm.hwconfig.devicetree);
(minor) the same as above

2023-03-24 10:31 UTC, lorc commented on Kconfig
> +config XEN_SHELL_CMDS
I am moving xen console srv to the separate library `XEN_CONSOLE_SRV`.

If I got this right, `XEN_SHELL` is used only for the shell commands. So, may I ask you to skip this commit? My PR will handle this in the other way around

2023-03-24 11:06 UTC, lorc commented on xrun/src/xrun.c
> +#if defined(CONFIG_XENVM_USE_GIC_V3)
@xakep-amatop , GICv3 **may** be backward compatible with GICv2. So on GICv3 machine we **may** support GICv2 for guests.

Anyways, there should be `XEN_DOMCTL_CONFIG_GIC_NATIVE`, I believe.

2023-03-24 13:10 UTC, firscity commented on Kconfig
> +	default 8129
Yes, but 8129 is not 8K (8129 -> 8192)

2023-03-24 17:54 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +			cmdline[pos++] = ' ';
fixed

2023-03-24 17:54 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +						spec->vm.kernel.parameters[i]);
+

2023-03-24 17:54 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	bytes_read = read_file(bundle, "config.json", config,
If we unable to read whole json - we won't parse it. I expect json with correct size in most cases (because app generates json and sets max size) so it will save us one call to storage.

2023-03-24 17:54 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	if (bytes_read < 0) {
yes. why not? If we can parse it.

2023-03-24 17:54 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +		LOG_ERR("Can't read config.json ret = %ld\n", bytes_read);
+

2023-03-24 17:54 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	ret = snprintf(container->kernel_image,
+

2023-03-24 17:54 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +					   "%s", spec.vm.hwconfig.devicetree);
+

2023-03-24 19:01 UTC, lorc reviewed
I do understand that time is pressing. So, I am okay with merging this changes as is, as far as you add **BIG FAT** `TODO` regarding object lifetime.

2023-03-24 19:42 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	int i, pos = 0;
I haven't added comments because completely rewritten func where i tried to cover all cases. Sorry, looks like this is an older comment.

2023-03-24 19:42 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	if (!container) {
Added big fat todo.

2023-03-24 19:47 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	if (!container) {
see above

2023-03-24 19:47 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	if (!container) {
see above

2023-03-24 19:47 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	*state = container->status;
see above

2023-03-24 19:50 UTC, xakep-amatop commented on xrun/include/storage.h
> + * @param size - size of the buffer
(question) where is description about skip paramr?

2023-03-24 20:02 UTC, xakep-amatop commented on xrun/src/storage.c
> +	if (rc == 0 && dirent.type == FS_DIR_ENTRY_FILE && dirent.size == 0) {
it is really interesting, why can't we have an empty files?..
I have looked on all usages of type and len and I haven't found any checks as you made here

it is true that every directory always has zero length, BUT file also may be with zero length, so I think your check is incorrect here

2023-03-24 20:04 UTC, xakep-amatop commented on xrun/src/storage.c
> +	char fname[LFS_NAME_MAX];
> In lfs.c line 2888 we can see the following check: nlen > lfs->name_max which is LFS_NAME_MAX
you should know that `lfs->name_max` is configurable and we have just default config this is the reason why you have seen `LFS_NAME_MAX`

2023-03-24 20:10 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	k_mutex_lock(&container_lock, K_FOREVER);
(note) just move alloc call above mutex lock and you can delete goto and lable at all

2023-03-24 20:11 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	if (bytes_read < 0) {
are you going to parse an empty buffer?

2023-03-24 20:39 UTC, oleksiimoisieiev commented on xrun/include/storage.h
> + * @param size - size of the buffer
+

2023-03-24 20:39 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	k_mutex_lock(&container_lock, K_FOREVER);
+

2023-03-24 20:39 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	if (bytes_read < 0) {
I'm sorry, but I thought I've already answered this question. I'm too tired for discussions. As for me personally - I don't see any problem with empty file or to check every step. I don't think there should be undefined behaviour or unexpected error here. Just tell what to do and I'll do that. That's it.

2023-03-24 20:40 UTC, xakep-amatop commented on xrun/src/xrun.c
> +		pos += snprintf(cmdline + pos, size - pos, "%s",
lets go to the sources:
[snprintf](https://elixir.bootlin.com/zephyr/latest/C/ident/snprintf) -> [cbvprintf](https://elixir.bootlin.com/zephyr/latest/C/ident/cbvprintf) -> [z_cbvprintf_impl](https://elixir.bootlin.com/zephyr/latest/C/ident/z_cbvprintf_impl)

and in case when you use function from file [cbprintf_nano.c](https://elixir.bootlin.com/zephyr/latest/source/lib/os/cbprintf_nano.c) it can't ret a negative value at all, but if the function is used from [cbprintf_complete.c](https://elixir.bootlin.com/zephyr/latest/source/lib/os/cbprintf_complete.c) it is possible to ret a negative value from `out` handler, at least you may find appropriate checks of ret code, but `out` handler can't return negative values ([sprintf_out](https://elixir.bootlin.com/zephyr/latest/C/ident/sprintf_out)), at least now...

my point is if function can return negative value you have to handle it in a proper way and don't care about internal realization, because it can be changed

2023-03-24 20:43 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	config = k_malloc(CONFIG_XRUN_JSON_SIZE_MAX);
you can avoid using of dynamic allocations and it is preferable way for zephyr code guidelines

2023-03-24 21:09 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	config = k_malloc(CONFIG_XRUN_JSON_SIZE_MAX);
Yes I can but we've discussed it on zehpyr channel.

2023-03-24 21:16 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	if (bytes_read < 0) {
it's json parser who's going to decide whether buffer is correct or not. At this point - it just reads file and doesn't know about it's contents. So why should it tread 0 size ar error?

2023-03-24 21:27 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	if (bytes_read < 0) {
I don't insist on any changes, I just have asked a few questions, because it was really unclear for me, I believe that a little comment helps to understand it more quickly by others too

2023-03-25 15:39 UTC, oleksiimoisieiev commented on xrun/src/storage.c
> +	if (rc == 0 && dirent.type == FS_DIR_ENTRY_FILE && dirent.size == 0) {
+

2023-03-25 15:44 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	if (bytes_read < 0) {
I'm not sure about comment. Let's ask what others are thinking?
@lorc  What do you think if I add the following comment:
"We don't check file size here because at this point the goal is to read the file. It's parser who will have to make a decision, whether file contents are ok or not".

2023-03-27 09:05 UTC, xakep-amatop commented on xrun/include/storage.h
> +ssize_t xrun_read_file(const char *path, char *buf,
(cosmetic) different names of first parameter here and in description

2023-03-27 09:11 UTC, xakep-amatop commented on xrun/src/xrun.c
> +	if (strlen(path) == 0 || strlen(name) == 0) {
(note) you can add extra two variables and avoid call of `strlen` second time below

2023-03-27 09:13 UTC, xakep-amatop commented on xrun/src/xrun.c
> +		k_free(fpath);
(note) you can move this mem free rigth after a call of `xrun_read_file` and simplify the code

2023-03-27 09:18 UTC, xakep-amatop commented
`Reviewed-by: Mykola Kvach <mykola_kvach@epam.com>`

2023-03-27 15:25 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +		k_free(fpath);
I've added after check because this approach seems to me more clear. And it's harder to miss k_free during refactoring

2023-03-27 16:28 UTC, firscity commented on xrun/src/xrun.c
> +	strncpy(container->container_id, container_id, CONTAINER_NAME_SIZE);
The only `sys_slist_append()` should be protected under the mutex.

2023-03-28 12:42 UTC, firscity commented
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2023-03-28 12:44 UTC, lorc commented
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2023-03-28 15:30 UTC, merged