Introduce dt_passthrough node support for domcfg
xen-troops/zephyr-xenlib pull request #17
Opened 2023-03-20 14:22 UTC by oleksiimoisieiev

Add dt_passthrough support to domcfg as analogue to dt_passthrough nodes in xl.cfg
This will allow us to pass nodes, that should be copied to the Domain device tree without need to put them to /passthrough node.

2023-03-20 16:56 UTC, firscity requested changes

2023-03-20 16:56 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +		goto out_dtb;
Curly braces?

2023-03-20 16:56 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	if (!dt_passthrough || nr_dt_passthrough == 0) {
Missing blank line after declaration.

2023-03-20 16:56 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	if (!dt_passthrough || nr_dt_passthrough == 0) {
Also, this function is static and such check is already present in calling code, so I think it is redundant.

2023-03-20 16:56 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +				return fdt_to_errno(rc);
You transferred dtb to heap with k_aligned_alloc(), but did not change error handling in this function. All return from this function will lead to leak of `fdt`.

2023-03-20 18:21 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	if (!dt_passthrough || nr_dt_passthrough == 0) {
fixed

2023-03-20 19:06 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	k_free(fdt);
Is this changes should be in previous commit? It is not related to dt_passthrough

2023-03-20 19:12 UTC, xakep-amatop requested changes

2023-03-20 19:12 UTC, xakep-amatop commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	for (i = 0; i < nr_dt_passthrough; i++) {
(cosmetic) comparison between signed and unsigned types

2023-03-20 19:23 UTC, xakep-amatop commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +void free_domain_fdt(void *fdt) {}
you can do the same but inside header file:
* add preprocessor if/else to header file and prototype/stub of function(s)
* build C file only in case when your condition is true, need to add some conditions to Makefile or Cmake, it depends on what is used inside the build system

2023-03-20 19:29 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	k_free(fdt);
fixed

2023-03-20 19:31 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	if (mapped_domd == NULL) {
fixed

2023-03-20 19:35 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +void free_domain_fdt(void *fdt) {}
Too complex as for me. You have to put conditional on 2 places instead of 1.

2023-03-20 19:37 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	k_free(fdt);
You probably forget to repush it, because I don't see any changes

2023-03-20 19:46 UTC, xakep-amatop approved these changes

2023-03-20 19:47 UTC, xakep-amatop commented
`Acked-by: Mykola Kvach <mykola_kvach@epam.com>`

2023-03-20 19:58 UTC, sa-kib commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +			return r;
this is not a critical error, we must not halt -- similar to libxl behaviour

2023-03-20 19:59 UTC, sa-kib commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +			LOG_ERR("Can't copy the node \"/%s\"",
dt_passthrough names already provide leading "/" in names, don't need to prepend it here

2023-03-20 20:40 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	k_free(fdt);
I can see changes. Please refresh page

2023-03-20 20:45 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +			LOG_ERR("Can't copy the node \"/%s\"",
+

2023-03-20 20:49 UTC, oleksiimoisieiev commented
Updated

2023-03-20 23:55 UTC, lorc commented
> This will allow us to pass nodes, that should be copied to the Domain device tree without need to put them to /passthrough node.

Do we really need this feature? It is considered  as ill-defined by the Xen community. This is why we can't upstream it to the Xen Tools.

2023-03-21 11:42 UTC, sa-kib commented
`Reviewed-by: Sergiy Kibrik <Sergiy_Kibrik@epam.com>` for patch [domain.h: Add dt_passthrough parameter to domain config](https://github.com/xen-troops/zephyr-xenlib/pull/17/commits/bfcf97e3952a03cafa42a806631ed92a9a31a77b)

2023-03-21 16:42 UTC, merged