xenstore-srv: refactor watch notification to avoid domain list reference
xen-troops/zephyr-xenlib pull request #18
Opened 2023-03-20 16:16 UTC by firscity

This commit changes Xenstore watches logic, to prevent xenstore-srv from using global domain list during watcher notification. Referencing to domain list without proper sycnronization between xen-dom-mgmt and xenstore-srv is risky and actually was not needed.

To notify watcher domain about file changes, we need to add pending event to global pevent list and notify domain with xb_sem. Previously, watch event holded only domid, which needed a domid_to_domain() calls for notification. Now we changed domid inside this structs to domain pointers to make direct notification possible and also fixed possible watches leaks during domain destroy. In this implementation all watches and pending events will be removed during domain destroy.

2023-03-20 19:21 UTC, oleksiimoisieiev requested changes

2023-03-20 19:21 UTC, oleksiimoisieiev commented on xenstore-srv/include/xenstore_srv.h
>  struct watch_entry {
Please run checkpatch. I've got 5 warnings.

2023-03-20 19:21 UTC, oleksiimoisieiev commented on xenstore-srv/src/xenstore_srv.c
> +	SYS_DLIST_FOR_EACH_CONTAINER(&watch_entry_list, iter, node) {
As I can see - all other iterations with watch_entry_list are done using FOR_EACH_ENTRY_SAFE, I looked through your part and don't see any problem with detached iterators but I could miss something. You don't necessary need to fix this. Just a tip to consider.

2023-03-21 00:10 UTC, lorc commented on xenstore-srv/src/xenstore_srv.c
> +				return;
The same comment about warning.

2023-03-21 00:10 UTC, lorc commented on xenstore-srv/src/xenstore_srv.c
> +			pentry->key[keyl - 1] = 0;
Again, why not `strcpy`?

2023-03-21 00:10 UTC, lorc commented on xenstore-srv/src/xenstore_srv.c
> +	char localpath[] = "/";
It is good to do some cleanup while reworking those parts. But you need to mention this in the commit message, at least.

Ideally - it should go to another commit.

2023-03-21 00:10 UTC, lorc commented on xenstore-srv/src/xenstore_srv.c
> +		if (domain->domid == iter->domain->domid) {
You can compare `domain` to `iter->domain`, no need to check IDs.

2023-03-21 00:10 UTC, lorc commented on xenstore-srv/src/xenstore_srv.c
> +			return;
It would be nice to return some error to the calling domain.

2023-03-21 00:10 UTC, lorc commented on xenstore-srv/src/xenstore_srv.c
> +			return;
It would be nice to return some error to the calling domain.

2023-03-21 00:10 UTC, lorc commented on xenstore-srv/src/xenstore_srv.c
> +			return;
It would be nice to return some error to the calling domain.

2023-03-21 00:10 UTC, lorc commented on xenstore-srv/src/xenstore_srv.c
> +			/* We can't notify domain so leave it without first WATCH_EVENT */
I believe, this is not the worst in this situation... At least we should output warning to the log.

2023-03-21 00:10 UTC, lorc commented on xenstore-srv/src/xenstore_srv.c
> +		if (entry->domain->domid == domain->domid) {
You can compare two domain pointers there.

2023-03-21 00:11 UTC, lorc commented
I do understand that the original code is messy. But it will be good to have code cleanup and logic changes in a different commits. If this is possible, of course.

2023-03-21 11:12 UTC, LKomaryanskiy commented on xenstore-srv/src/xenstore_srv.c
> +
cosmetic: please, remove two newlines

2023-03-21 11:31 UTC, LKomaryanskiy commented on xenstore-srv/src/xenstore_srv.c
> +	wentry = key_to_watcher(path, true, token);
Also, key_to_watcher and fire_watcher make access to watch_entry_list without wel_mutex lock. Could you please check if is it ok?

2023-03-21 11:42 UTC, LKomaryanskiy commented on xenstore-srv/src/xenstore_srv.c
> +	wentry = key_to_watcher(path, true, token);
BTW, key_to_watcher returns pointer to wentry but I assume, that it can be situation, when after that can be called function that will free wentry via remove_watch_entry, so assigning wentry->is_relative will lead to use after free issue.

2023-03-21 18:27 UTC, firscity commented on xenstore-srv/src/xenstore_srv.c
> +
Thanks, done.

2023-03-21 18:31 UTC, firscity commented on xenstore-srv/src/xenstore_srv.c
> +	wentry = key_to_watcher(path, true, token);
> As I see, this function is called in two places, and in both cases second parameter (complete) is true. Maybe is it better to remove it at all?

I think it is somehow related to watches to directories. I will check it in further PR, xenstore is not fully implemented now.

> Also, key_to_watcher and fire_watcher take access to watch_entry_list without wel_mutex lock. Could you please check if is it ok?

> BTW, key_to_watcher returns pointer to wentry but I assume, that it can be situation, when after that can be called function that will free wentry via remove_watch_entry, so assigning to wentry->is_relative can situably lead to use after free memory issue.

No, probably it is not. Fixing require some time, I'm currently working on it. I fixed only call to `key_to_watcher` in my PR, please check.

2023-03-24 10:21 UTC, LKomaryanskiy approved these changes

2023-03-24 10:28 UTC, lorc commented
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2023-03-24 14:49 UTC, xakep-amatop commented on xenstore-srv/src/xenstore_srv.c
> +	k_mutex_lock(&wel_mutex, K_FOREVER);
(question major) Why didn't you check status here?
```
 * @retval 0 Mutex locked.
 * @retval -EBUSY Returned without waiting.
 * @retval -EAGAIN Waiting period timed out.
 */
__syscall int k_mutex_lock(struct k_mutex *mutex, k_timeout_t timeout);
```

2023-03-24 14:49 UTC, xakep-amatop commented on xenstore-srv/src/xenstore_srv.c
> +		snprintf(path, STRING_LENGTH_MAX, "/local/domain/%d/%s",
(note) this function can return negative error code  or 0

2023-03-24 14:49 UTC, xakep-amatop commented on xenstore-srv/src/xenstore_srv.c
> +			 domain->domid, payload);
(question) could you please add check if you have enough space inside buffer ?

2023-03-24 14:49 UTC, xakep-amatop commented on xenstore-srv/src/xenstore_srv.c
>  	memcpy(token, payload + plen, len - plen);
(major) could you pls add extra checking if we have enough space inside `token`:
```
if (sizeof(token) < len - plen)
```
**possible stack corruption here**

2023-03-24 14:49 UTC, xakep-amatop commented on xenstore-srv/src/xenstore_srv.c
> +	wentry = key_to_watcher(path, true, token);
(note/not your issue) as far as I see this function is used only inside this file, but it hasn't `static` keyword

2023-03-24 14:49 UTC, xakep-amatop commented on xenstore-srv/src/xenstore_srv.c
> +		memcpy(wentry->token, token, len - plen);
(note) you limit buffer on stack, but don't limit buffers during allocations of `key` and `token`
as for me it will be better to put key and token as an arrays inside `wentry` and use only one alloc for `wentry`

moreover, `len - plen` can be bigger than size of `token`

how much memory did you save and how much CPU cycles waste for a few allocations?

2023-03-24 14:49 UTC, xakep-amatop commented on xenstore-srv/src/xenstore_srv.c
> +		snprintf(path, STRING_LENGTH_MAX, "/local/domain/%d/%s",
(note) better to use sizeof here instead of `STRING_LENGTH_MAX` in this case if somebody changes len of path array you don't need to change it in all places

2023-03-27 09:46 UTC, firscity reviewed
Thanks for review, please check updates.

2023-03-27 09:46 UTC, firscity commented on xenstore-srv/src/xenstore_srv.c
> +		if (strncmp(iter->key, path, strlen(iter->key)) == 0) {
Done

2023-03-27 09:46 UTC, firscity commented on xenstore-srv/src/xenstore_srv.c
> +	full_plen = strlen(path) + 1;
Done

2023-03-27 11:15 UTC, xakep-amatop commented on xenstore-srv/src/xenstore_srv.c
> +		if (full_plen < 0) {
(note) `full_plen` can be equal to zero

2023-03-27 11:16 UTC, xakep-amatop approved these changes
`Reviewed-by: Mykola Kvach <mykola_kvach@epam.com>`

2023-03-27 19:42 UTC, oleksiimoisieiev commented on xenstore-srv/src/xenstore_srv.c
> +	} else {
k_mutex_unlock in both conditions. it can be placed before if

2023-03-27 19:42 UTC, oleksiimoisieiev commented on xenstore-srv/src/xenstore_srv.c
> +		if (full_plen < 0) {
Hm. snprintf will return at least strlen("/local/domain/"). it can return 0 only if sizeof(path) = 0, which is unlikely. As for me - check for 0 here is redundand

2023-03-28 10:37 UTC, oleksiimoisieiev commented on xenstore-srv/src/xenstore_srv.c
> +	} else {
Ok.

2023-03-28 10:47 UTC, merged