xenlib: add vch library headers
xen-troops/zephyr-xenlib pull request #2
Opened 2023-02-20 10:06 UTC by sa-kib

Emplace initial structure of vchan implementation.

2023-02-20 14:31 UTC, firscity requested changes
Also, please add more detailed commit message with motivation for this change.

2023-02-20 14:31 UTC, firscity commented on vch/include/vch.h
> +#pragma once
Please, add SPDX identifier and EPAM copyright to newly created file

2023-02-20 14:50 UTC, firscity commented
Also, please look at Zephyr checkpatch output for you PR:
```
...
WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
#52: FILE: vch/include/vch.h:1:
+#pragma once

WARNING: Prefer 'unsigned int' to bare use of 'unsigned'
#62: FILE: vch/include/vch.h:11:
+	unsigned write_ord;

ERROR: "(foo*)" should be "(foo *)"
#70: FILE: vch/include/vch.h:19:
+void vch_close(struct vch_handle*);
...

```

2023-02-23 08:46 UTC, sa-kib commented on vch/CMakeLists.txt
> +add_library(VCH INTERFACE)
added in 28be6bf

2023-02-23 08:46 UTC, sa-kib commented on vch/include/vch.h
> +#pragma once
added in 28be6bf

2023-02-23 08:47 UTC, sa-kib commented on vch/include/vch.h
> +int vch_open(domid_t, const char *path, size_t min_rs, size_t min_ws, struct vch_handle*);
added in 28be6bf

2023-02-23 08:47 UTC, sa-kib commented
> Also, please add more detailed commit message with motivation for this change.

commit msg updated

2023-02-23 09:33 UTC, firscity commented
Please, add my `Reviewed-by: Dmytro Firsov <dmytro_firsov@epam.com>` and force-push squashed commit.

2023-02-23 09:33 UTC, firscity approved these changes

2023-02-23 10:06 UTC, sa-kib commented
squashed & rebased

2023-02-23 10:23 UTC, merged