vch: initial implementation
xen-troops/zephyr-xenlib pull request #20
Opened 2023-03-21 16:46 UTC by sa-kib

Introduce vchannels basic support -- order 10 or order 11 shared ring size within single page (no arbitrary sized rings across multiple pages yet), stream-based read/write from/to vchannel, blocking I/O support, notifications support.

2023-03-22 10:10 UTC, oleksiimoisieiev requested changes

2023-03-22 10:10 UTC, oleksiimoisieiev commented on vch/src/vch.c
> +	k_sem_take(&h->sem, K_FOREVER);
k_sem_take may fail

2023-03-22 10:10 UTC, oleksiimoisieiev commented on vch/src/vch.c
> +	snprintf(xs_key_scratch, sizeof(xs_key_scratch),
snprintf may return error

2023-03-22 10:10 UTC, oleksiimoisieiev commented on vch/src/vch.c
> +	char xs_key_scratch[64] = { 0 };
I'd rather make size as define. because it's reused in 2 functions

2023-03-22 10:10 UTC, oleksiimoisieiev commented on vch/src/vch.c
> +	if (!remote_port)
empty line and please run checkpatch

2023-03-22 10:10 UTC, oleksiimoisieiev commented on vch/src/vch.c
> +	if (size > RD_RING_SZ(h) || !h || !buf)
I think you should check if h != 0 before doing RD_RING_SZ

2023-03-22 10:10 UTC, oleksiimoisieiev commented on vch/src/vch.c
> +		if (!avail) {
Cosmetic. this could be rewritten as 
if (avail) {
   break;
}

2023-03-22 10:10 UTC, oleksiimoisieiev commented on vch/src/vch.c
> +		if (!avail) {
same as above

2023-03-24 08:31 UTC, sa-kib commented on vch/src/vch.c
> +	k_sem_take(&h->sem, K_FOREVER);
indeed, yet here we can't propagate or return error anyway

2023-03-24 08:39 UTC, sa-kib commented on vch/src/vch.c
> +	if (!h || !h->ring)
checkpatch.pl told me to remove braces from this single-statement condition

2023-03-24 08:55 UTC, sa-kib commented on vch/src/vch.c
> +	memset(h, 0, sizeof(*h));
fixed

2023-03-24 08:55 UTC, sa-kib commented on vch/src/vch.c
> +	if (size > RD_RING_SZ(h) || !h || !buf)
fixed

2023-03-24 08:55 UTC, sa-kib commented on vch/src/vch.c
> +		if (!avail) {
rewritten

2023-03-24 08:56 UTC, sa-kib commented on vch/src/vch.c
> +		if (!avail) {
rewritten

2023-03-24 09:14 UTC, firscity commented on vch/src/vch.c
> +	h->ring = k_aligned_alloc(XEN_PAGE_SIZE, XEN_PAGE_SIZE);
FYI: you can just use `gnttab_alloc_and_grant`

2023-03-24 09:14 UTC, firscity commented on vch/src/vch.c
> +	map.host_addr = (uintptr_t)h->ring;
Please, use `xen_to_phys()`

2023-03-24 09:14 UTC, firscity commented on vch/src/vch.c
> +		map.host_addr = (uintptr_t)h->ring;
Please, use `xen_to_phys()`

2023-03-24 09:14 UTC, firscity commented on vch/src/vch.c
> +		dmb();
What is the point of this barrier after you checked the ring values?

2023-03-24 10:26 UTC, lorc commented on vch/src/vch.c
> +	__ASSERT(h, "Invalid handler");
AFAIR, you need to return an error in this case. `vch_open` is externally visible, so using `__ASSERT` in an input parameter is not a best idea. ASSERTs usually used for checking internal state of a module.

2023-03-24 10:26 UTC, lorc commented on vch/src/vch.c
> +	__ASSERT(h, "Invalid handler");
The same comment about input parameters

2023-03-24 10:26 UTC, lorc commented on vch/src/vch.c
> +	RD_CONS(h) += size;
You need `dmb()` after this, not before. Other side needs to see write completed before calling `vch_notify`

2023-03-24 10:26 UTC, lorc commented on vch/src/vch.c
> +	dmb();
Why this `dmb` is needed?

2023-03-24 10:26 UTC, lorc commented on vch/src/vch.c
> +	vch_notify(h, VCHAN_NOTIFY_WRITE);
The same about `dmb`

2023-03-24 10:51 UTC, LKomaryanskiy commented on vch/src/vch.c
> +	if (rc)
Please, add curly braces here and below in the function.

2023-03-24 10:51 UTC, LKomaryanskiy commented on vch/src/vch.c
> +	if (rc)
Please, add curly braces here and below in the function.

2023-03-24 10:51 UTC, LKomaryanskiy commented on vch/src/vch.c
> +	if (!h)
Please, add curly braces here.

2023-03-24 10:51 UTC, LKomaryanskiy commented on vch/src/vch.c
> +	if (!h || size > WR_RING_SZ(h) || !buf)
Please, add curly braces here and below in the function.

2023-03-24 10:51 UTC, LKomaryanskiy commented on vch/src/vch.c
> +	unmask_event_channel(h->evtch);
nit: as I see unmask_event_channel return error code. Despite currently it always returns 0, it can be changed later and will return error code. So it's better to add here a check of it.

2023-03-24 10:51 UTC, LKomaryanskiy commented on vch/src/vch.c
> +	gnttab_end_access(ring_gref);
(question): The function can return error code. Should we act somehow or print some massage in case of error?

2023-03-24 10:51 UTC, LKomaryanskiy commented on vch/src/vch.c
> +	unbind_event_channel(h->evtch);
The same as for unmask_event_channel. I write this because if I'm not mistaken, Zephyr code style requires checking error code for every function.

2023-03-24 10:51 UTC, LKomaryanskiy commented on vch/src/vch.c
> +	notify_evtchn(h->evtch);
As I see, notify_evtchn can return error code. Please add check for it.

2023-03-24 10:51 UTC, LKomaryanskiy commented on vch/src/vch.c
> +	if (!h || size > RD_RING_SZ(h) || !buf)
Please, add curly braces here and below in the function.

2023-03-24 11:17 UTC, sa-kib commented on vch/src/vch.c
> +	ring_gref = rc;
fixed in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:18 UTC, sa-kib commented on vch/src/vch.c
> +	if (!remote_port)
done [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:18 UTC, sa-kib commented on vch/src/vch.c
> +	char xs_key_scratch[64] = { 0 }, xs_val_scratch[8] = { 0 };
done in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:19 UTC, sa-kib commented on vch/src/vch.c
> +	h->ring = k_aligned_alloc(XEN_PAGE_SIZE, XEN_PAGE_SIZE);
done in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:19 UTC, sa-kib commented on vch/src/vch.c
> +		map.host_addr = (uintptr_t)h->ring;
done in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:21 UTC, sa-kib commented on vch/src/vch.c
> +		dmb();
I thought that if (avail) condition might be re-ordered w/ f (h->blocking) condition, as they're not inter-dependent and we don't ever change RD_PROD(h) in this code. So barrier is for covering this case.

2023-03-24 11:22 UTC, sa-kib commented on vch/src/vch.c
> +	__ASSERT(h, "Invalid handler");
fixed in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:22 UTC, sa-kib commented on vch/src/vch.c
> +	__ASSERT(h, "Invalid handler");
fixed in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:22 UTC, sa-kib commented on vch/src/vch.c
> +	RD_CONS(h) += size;
indeed, fixed in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:22 UTC, sa-kib commented on vch/src/vch.c
> +	dmb();
on the second thought, not needed, removed in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:23 UTC, sa-kib commented on vch/src/vch.c
> +	if (rc)
done in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:23 UTC, sa-kib commented on vch/src/vch.c
> +	if (rc)
done [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:23 UTC, sa-kib commented on vch/src/vch.c
> +	if (!h)
done in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:23 UTC, sa-kib commented on vch/src/vch.c
> +	if (!h || size > WR_RING_SZ(h) || !buf)
done in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 11:25 UTC, sa-kib commented on vch/src/vch.c
> +	if (!h || size > RD_RING_SZ(h) || !buf)
done in [8eb23b6](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/8eb23b6fb030f2017287c1f94e9f89507c316797)

2023-03-24 13:20 UTC, sa-kib commented on vch/src/vch.c
> +	notify_evtchn(h->evtch);
done in [4ec290a](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/4ec290aed31ea4d0d0a1a80f64ac706c4215dac3)

2023-03-24 13:25 UTC, sa-kib commented on vch/src/vch.c
> +	gnttab_end_access(ring_gref);
library prints no messages, just passes error codes.
Besides, this part supposed to handle error that already took place before, we can't mitigate or fix it here, so additional messages would add no useful or meaningful info.

2023-03-24 13:27 UTC, sa-kib commented on vch/src/vch.c
> +	RD_CONS(h) += size;
turns out message exchange does not work if we move this barrier (gets stuck), so 
I'll leave where it was before.

2023-03-24 15:02 UTC, xakep-amatop commented on vch/include/vch.h
> +	char path[32];
(question) is this len for path enough?

2023-03-25 13:47 UTC, xakep-amatop commented on vch/src/vch.c
> +	return notify_evtchn(h->evtch);
(question) should you call `unbind_event_channel` and `gnttab_unmap_refs` in case of error ?

2023-03-25 13:47 UTC, xakep-amatop commented on vch/src/vch.c
> +		goto free_evtch;
(question) should you call `gnttab_put_page` here too?

2023-03-25 13:47 UTC, xakep-amatop commented on vch/src/vch.c
> +	} while (true);
(question) Do we need to add some timeout checking here and for the next function?

2023-03-25 13:47 UTC, xakep-amatop commented on vch/src/vch.c
>  int vch_read(struct vch_handle *h, void *buf, size_t size)
(question) should you add so,e protection mechanisms for reader and writer? what is happened if two or more different CPUs call write function at the same time and get the same `avail`?
who guarantees that function call will be atomic?

2023-03-28 08:29 UTC, firscity commented on vch/src/vch.c
> +		dmb();
If I understood you correctly, then it also will not fix your problem. This barrier will not prevent `if (avail)` and `if (h->blocking)` from reordering. @lorc, please correct me if I'm wrong.

2023-03-28 08:29 UTC, firscity commented on vch/src/vch.c
> +	RD_CONS(h) += size;
@lorc please, take a look.

2023-03-28 10:59 UTC, lorc commented on vch/src/vch.c
> +		dmb();
Actually, this `DMB` is needed to prevent accessing data before accessing ring counters.

Comments in Xen's "tools/libs/vchan/io.h" describe pretty good why do we need barriers there.

2023-03-28 10:59 UTC, lorc commented on vch/src/vch.c
> +	RD_CONS(h) += size;
I was mistaken in this case, I'm sorry, Yes, you need `DMB` between data write and `cons` update.

2023-04-06 16:10 UTC, sa-kib commented on vch/src/vch.c
> +	val = __atomic_fetch_and(target, ~rw, __ATOMIC_SEQ_CST);
because of parameter's types -- it requires target to be `atomic_t` yet in our case it's `uint8_t`

2023-04-06 16:32 UTC, xakep-amatop commented on vch/src/vch.c
> +#define SERVER_CONNECTED 1
```
In general, enums should be used when defining a small set of related constants that are used within a single module or function. They are useful when type safety is important, as they prevent incorrect assignments and can make code more modular. They are also easier to use and debug than #define.

#Define should be used when defining global constants or macros that are used throughout a program. They are useful for defining constants that are not related to a particular type, such as buffer sizes or maximum values. They are also useful for defining macros that perform operations, such as inline functions or conditional compilation.

In conclusion, while both enums and #define are useful for defining constants in C, enums should be used when type safety, scope, and ease of use are important, and #define should be used when defining global constants or macros that are used throughout a program.
```

2023-04-06 17:24 UTC, sa-kib commented on vch/src/vch.c
> +	struct gnttab_map_grant_ref map;
should be ok, all of these are not used before initialization

2023-04-06 17:29 UTC, sa-kib commented on vch/src/vch.c
> +	} while (true);
will discuss it w/ aos folks

2023-04-06 17:31 UTC, sa-kib commented on vch/src/vch.c
>  int vch_read(struct vch_handle *h, void *buf, size_t size)
the one who uses zephyr-xenlib from multiple CPUs is already screwed up

2023-04-06 17:33 UTC, sa-kib commented on vch/src/vch.c
> +	memset(h, 0, sizeof(*h));
will discuss w/ aos folks

2023-04-06 17:47 UTC, sa-kib commented on vch/src/vch.c
> +		h->read_ord = 10;
done in [4a07f64](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/4a07f64cfbce74878daeea03d3a61a88fa476666)

2023-04-06 17:48 UTC, sa-kib commented on vch/src/vch.c
> +		goto free_evtch;
fixed in [4a07f64](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/4a07f64cfbce74878daeea03d3a61a88fa476666)

2023-04-06 17:48 UTC, sa-kib commented on vch/src/vch.c
> +	return notify_evtchn(h->evtch);
yes, done in [4a07f64](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/4a07f64cfbce74878daeea03d3a61a88fa476666)

2023-04-06 17:48 UTC, sa-kib commented on vch/src/vch.c
> +		goto free_evtch;
yes, done in [4a07f64](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/4a07f64cfbce74878daeea03d3a61a88fa476666)

2023-04-06 18:13 UTC, sa-kib commented on vch/src/vch.c
> +	if (!h->ring)
done in [7121c25](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/7121c25b28dd4a319908167d04f588af3e47c63f)

2023-04-06 18:14 UTC, sa-kib commented on vch/include/vch.h
> +	char path[32];
done in [609d7fe](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/609d7fe8e4884d2c51772f4b1dac76dfe1223481)

2023-04-06 18:15 UTC, sa-kib commented on vch/src/vch.c
> +	strncpy(h->path, path, MIN(sizeof(h->path) - 1, strlen(path)));
I shall disallow too long paths, see [609d7fe](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/609d7fe8e4884d2c51772f4b1dac76dfe1223481)

2023-04-06 18:17 UTC, sa-kib commented on vch/src/vch.c
> +	if (!h) {
done in [609d7fe](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/609d7fe8e4884d2c51772f4b1dac76dfe1223481)

2023-04-06 18:17 UTC, sa-kib commented on vch/src/vch.c
> +	if (!h) {
done in [609d7fe](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/609d7fe8e4884d2c51772f4b1dac76dfe1223481)

2023-04-06 19:46 UTC, xakep-amatop commented on vch/src/vch.c
> +	val = __atomic_fetch_and(target, ~rw, __ATOMIC_SEQ_CST);
get it , thanks

GCC documentation states that atomic operations on memory require properly aligned memory addresses. Attempting to perform atomic operations on unaligned memory addresses can lead to undefined behavior.

Here is a relevant excerpt from the GCC documentation on atomic built-in functions:

```
Atomic memory access functions (__atomic_fetch_..., etc.) require that the memory operand is naturally aligned. Unaligned memory operands can result in undefined behavior.
```

could you please check that pointer is aligned?

2023-04-06 22:45 UTC, lorc commented on vch/src/vch.c
> +	val = __atomic_fetch_and(target, ~rw, __ATOMIC_SEQ_CST);
`uint8_t` is always naturally aligned.

2023-04-14 09:30 UTC, sa-kib commented
squashed & rebased, because too much of fixups accumulated

2023-04-14 09:30 UTC, sa-kib commented on vch/src/vch.c
> +	memset(h, 0, sizeof(*h));
as per discussion it has been decided to leave interface w/o modifications

2023-04-14 09:30 UTC, sa-kib commented on vch/src/vch.c
> +	} while (true);
as per discussion it has been decided to leave interface w/o modifications

2023-04-19 08:02 UTC, sa-kib commented on vch/src/vch.c
> +	snprintf(xs_key_scratch, sizeof(xs_key_scratch),
strncpy() always returns pointer to destination (in zephyr at least)

2023-04-19 08:05 UTC, sa-kib commented on vch/src/vch.c
> +	unbind_event_channel(h->evtch);
library prints no messages, and here we can't do much if calls would fail

2023-04-19 08:06 UTC, lorc commented on vch/src/vch.c
> +
I believe, you need `dmb` there to ensure that you actually read indexes before accessing the data. Libvchan has `xen_rmb()` at this position in the code.

2023-04-19 08:06 UTC, lorc commented on vch/src/vch.c
> +
I believe, you need dmb there to ensure that you actually read indexes before accessing the data. Libvchan has `xen_rmb()` at this position in the code.

2023-04-19 08:55 UTC, oleksiimoisieiev requested changes

2023-04-19 08:55 UTC, oleksiimoisieiev commented on vch/include/vch.h
> +#ifndef CONFIG_VCH_PATH_MAXLEN
It seems to me that this should be moved to KConfig. See commit fb8763aeef4fe9021686607f3c351c3f62224880 XRUN_JSON_SIZE_MAX as example. And with default value ifndef is not needed here

2023-04-19 10:34 UTC, sa-kib commented on vch/src/vch.c
> +		goto free_evtch;
it won't be freed, there's conditional free at `free_evtch` label

2023-04-19 10:39 UTC, lorc commented on vch/src/vch.c
> +		goto free_evtch;
Yes, I saw that. This is somewhat minor, but nevertheless this code does not look right. You can just `return rc` and it will not cause WTF moment for anyone who reads this code.

2023-04-19 10:44 UTC, sa-kib commented on vch/src/vch.c
> +	rc = xss_set_perm(xs_key_scratch, domain, XS_PERM_READ);
permissions set explicitly because it can't be provided to `xss_write()` as parameter and set atomically. However `xss_set_perm()` is a placeholder and doesn't really touch any permissions at all. Should this call be removed then?

2023-04-19 10:52 UTC, sa-kib commented on vch/src/vch.c
> +
https://github.com/xen-troops/zephyr-xenlib/pull/20#discussion_r1147390199

we were here already

2023-04-19 10:54 UTC, sa-kib commented on vch/src/vch.c
> +
we looked here already: https://github.com/xen-troops/zephyr-xenlib/pull/20#discussion_r1147390803

2023-04-19 11:00 UTC, lorc commented on vch/src/vch.c
> +
Well, in that comment I asked why it is needed :) I didn't ask to remove it... Actually, it seems that we need it to ensure that we see (and read) changes to prod/cons before accessing data buffer

2023-04-19 14:08 UTC, sa-kib commented on vch/src/vch.c
> +	rc = xss_set_perm(xs_key_scratch, domain, XS_PERM_READ);
transactions not supported by `xenstore-srv` implementation of XS, that is why it hasn't been used at the first place

2023-04-19 14:27 UTC, sa-kib commented on vch/src/vch.c
> +	__ASSERT(h, "Invalid handler");
fixed in [426b786](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/426b78633decf265e3e014be31be346733c54eb9)

2023-04-19 14:27 UTC, sa-kib commented on vch/src/vch.c
> +	__ASSERT(h, "Invalid handler");
fixed in [426b786](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/426b78633decf265e3e014be31be346733c54eb9)

2023-04-19 14:31 UTC, sa-kib commented on vch/src/vch.c
> +		goto free_evtch;
ok, done in [426b786](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/426b78633decf265e3e014be31be346733c54eb9)

2023-04-19 14:32 UTC, sa-kib commented on vch/src/vch.c
> +
done in [426b786](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/426b78633decf265e3e014be31be346733c54eb9)

2023-04-19 14:32 UTC, sa-kib commented on vch/include/vch.h
> +#ifndef CONFIG_VCH_PATH_MAXLEN
done in [426b786](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/426b78633decf265e3e014be31be346733c54eb9)

2023-04-19 14:34 UTC, sa-kib commented on vch/src/vch.c
> +	_vch_unmask_notify(h, VCHAN_NOTIFY_WRITE);
if no enough data was put into ring we request the sender to send a signal when the data gets written. It can be moved outside of this helper ofc, done in [9530e76](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/9530e7663ba7bf5ea0c29814b525b8ad596e138b)

2023-04-19 14:40 UTC, lorc commented on vch/src/vch.c
> +	rc = xss_set_perm(xs_key_scratch, domain, XS_PERM_READ);
Okay, this is the problem. Then you need to provide "TODO" comment with problem description, so we can fix it later.

Absence of transactions can (and will) lead to hard-to-debug problems with synchronization. Because the other side expects to find both `ring-ref` and `event-channel` entries at the same time. And with current code it is possible that it will see only `ring-ref` because `event-channel` is not yet ready.

2023-04-19 16:05 UTC, oleksiimoisieiev commented
Acked-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>

2023-04-19 18:38 UTC, sa-kib commented on vch/src/vch.c
> +	rc = xss_set_perm(xs_key_scratch, domain, XS_PERM_READ);
done in [1150f86](https://github.com/xen-troops/zephyr-xenlib/pull/20/commits/1150f86f00943b62d81654aeba992daebe1df0f7)

2023-04-20 07:35 UTC, sa-kib commented
squashed-rebased w/ tags added

2023-04-20 08:18 UTC, LKomaryanskiy commented
Good job!
`Acked-by: Leonid Komarianskyi <leonid_komarianskyi@epam.com>`

2023-04-20 08:19 UTC, firscity approved these changes
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2023-04-20 08:45 UTC, xakep-amatop approved these changes
`Acked-by: Mykola Kvach <mykola_kvach@epam.com>`

2023-04-20 10:37 UTC, merged