Rework Xen Console driver
xen-troops/zephyr-xenlib pull request #21
Opened 2023-03-24 18:38 UTC by lorc

Now you can use `xu console_attach -d NNN` command to attach to a domain console.

2023-03-25 14:51 UTC, xakep-amatop commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	xen_stop_domain_console(domain);
(question) should you add checking of error code here?

2023-03-25 14:51 UTC, xakep-amatop commented on xen-shell-cmd/src/xen_cmds.c
>  LOG_MODULE_DECLARE(xen_shell);
(major) pls, change this macro to `LOG_MODULE_REGISTER`, because we don't have register macro anymore after deleting of `xen_shell.c` file

2023-03-25 14:51 UTC, xakep-amatop commented on xen-console-srv/src/xen_console.c
> +	for (i = 0; i < DOM_MAX; i++)
(cosmetic) pls, add curly braces

2023-03-25 14:51 UTC, xakep-amatop commented on xen-console-srv/src/xen_console.c
> +static uint32_t used_threads;
(question) Is it enough for us to have 32-threads?

2023-03-25 14:51 UTC, xakep-amatop commented on xen-console-srv/src/xen_console.c
> +	for (i = 0; i < DOM_MAX; i++)
(note) looks like you can do it faster:
```
uint32_t inv = ~used_threads;
if (inv) {
    ret = __builtin_ffs(inv) - 1;
    used_threads |= BIT(ret);
    LOG_DBG("Allocated stack with index %d\n", i);
}
```

2023-03-25 14:51 UTC, xakep-amatop commented on xen-console-srv/src/xen_console.c
> +BUILD_ASSERT((XEN_CONSOLE_BUFFER_SZ & (XEN_CONSOLE_BUFFER_SZ - 1)) == 0);
(note) it isn't work for case when `XEN_CONSOLE_BUFFER_SZ` is equal to `0`, could you please add extra check for it?

2023-03-27 11:54 UTC, LKomaryanskiy commented on xen-console-srv/src/xen_console.c
> +		return rc;
(question) Should we add some error message here?

2023-03-27 11:54 UTC, LKomaryanskiy commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	xen_stop_domain_console(domain);
Sorry for answering not for me question, but I did this in my PR:
https://github.com/xen-troops/zephyr-xenlib/pull/13/commits/15033fb61edf5764dc898a6ef907d92cacbe8e46
I will rebase it after @lorc PR will be merged.

2023-03-27 11:54 UTC, LKomaryanskiy commented on xen-console-srv/src/xen_console.c
> +	k_free(console->int_buf);
As I see, stopping the thread executed after this line and perhaps at this time gap console_feed_int_ring that uses console->int_buf can be invoked. Seems like can it lead to use after free issue, or not?

2023-03-27 13:55 UTC, xakep-amatop requested changes

2023-03-27 13:55 UTC, xakep-amatop commented on xen-console-srv/src/xen_console.c
> +	write_to_ext_ring(console->intf, data, len);
(question major) why didn't you protect writes with some locks/mutexes?
as far as I see, you protected reads, I think that can be some concurrency problems on multicore systems related to `intf->in_prod`

2023-03-27 13:55 UTC, xakep-amatop commented on xen-console-srv/src/xen_console.c
> +				size_t buf_pos = (console->int_cons++) %
(note) fill free to use `&` instead of `%`, because `XEN_CONSOLE_BUFFER_SZ` is power of two

2023-03-27 13:55 UTC, xakep-amatop commented on xen-console-srv/src/xen_console.c
> +	if (!console->first_attach) {
(question) is it better to use here atomic cmp xchg or even console lock ?

2023-03-27 14:14 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +static uint32_t used_threads;
`DOM_MAX` is `4` right now, so no problems right now. We can easily extend this variable to `uint64_t` if there will be need. And if we ever need to run more than 64 DomUs, we will have more serious problems, than this.

Also, note that I'm adding `BUILD_ASSERT` just in case.

2023-03-27 14:15 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +	for (i = 0; i < DOM_MAX; i++)
Good idea, thanks.

2023-03-27 14:16 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +		goto err_free;
No, I should not. Why?

2023-03-27 14:17 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +	k_free(console->int_buf);
Ahh, good catch. Thank you. I need to revisit this part.

2023-03-27 14:21 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +	char buf[32];
There is the comment right before this. I see no profit in moving this into define, as it is used exactly in one place and is not this important. 

But,  if you insist, I can add a separate define like `XEN_CONSOLE_TEMPORARY_BUF_SIZE`

2023-03-27 14:23 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +	write_to_ext_ring(console->intf, data, len);
Because this is an inter-domain ring buffer. There are no lock by definition. Correctness of operation is guaranteed by correct data barrier use. Please see the `xen_console: use correct barriers` patch for more information.

2023-03-27 14:24 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +	if (!console->first_attach) {
Do you have particular reason to suggest using locking or atomic ops in this case?

2023-03-27 14:51 UTC, xakep-amatop commented on xen-console-srv/src/xen_console.c
> +	if (!console->first_attach) {
race condition between init and attach

2023-03-27 19:15 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +	k_free(console->int_buf);
If console initialization fails, it is expected that domain instance will be destroyed immediately. So there is no great need to re-assign the pointer.

2023-03-27 19:15 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +	if (!console->first_attach) {
It is expected that attach will never be called if init is incomplete:

1. This is common pattern: user must ensure that they don't try to use not-initialized modules. Actually, it is very hard to prevent use-before-init from inside a module. For example, in this case you can't use `console->lock` because it may be not initialized yet.

2. In this particular case, domain will not be created if console is not properly initialized. So you can't get valid `struct domain *` pointer to pass it to `attach`

2023-03-27 19:15 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +		goto err_free;
If initialization of console fails, domain will not be created at all. User will not have valid `struct domain*` pointer to pass it to `attach`. Also, please note, that you **want** `first_attach` to be `true`, otherwise `attach` function will call `k_thread_attach` on invalid pointer.

2023-03-27 19:36 UTC, lorc commented on xen-console-srv/src/xen_console.c
> +		return rc;
Actually, after reworking `get_stack_idx` is guaranteed to return a valid value.

2023-03-27 19:52 UTC, xakep-amatop commented on xen-console-srv/src/xen_console.c
> +	if (!console->first_attach) {
thanks for explanations

2023-03-27 20:05 UTC, xakep-amatop approved these changes
`Acked-by: Mykola Kvach <mykola_kvach@epam.com>`

2023-03-28 11:30 UTC, firscity commented on xen-console-srv/src/xen_console.c
> +		goto err_free;
Old problem: here should be smth like `goto unbind_evtchn` for `console->local_evtchn`, that was taken previously.

2023-03-28 11:30 UTC, firscity commented on xen-console-srv/src/xen_console.c
> +	ARG_UNUSED(p2);
This line is invalid, if you are using `p2` as shell pointer.

2023-03-28 11:51 UTC, firscity approved these changes
Amazing job, thank you!
`Reviewed-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2023-03-28 12:03 UTC, merged