xenstat initial commit
xen-troops/zephyr-xenlib pull request #29
Opened 2023-04-06 13:17 UTC by dsemenets

2023-04-07 07:32 UTC, oleksiimoisieiev requested changes

2023-04-07 07:32 UTC, oleksiimoisieiev commented on Kconfig
> +config XSTAT_SHELL_CMDS
depends on instead of if?

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/include/xstat.h
> +#ifndef _XSTAT_H
Was is taken from xl? If yes I assume copyright should be added

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +#define XENVER_version      0
strange comment

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	major = ret >> 16;
need empty line

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +int xstat_version(const struct shell *shell)
I think this should be splitted to 2 parts: the first part is here to return extra version in result of API call, And second, which should be in shell cmds and show extraversion in shell.

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +
if (!stat) {
return ...

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	sprintf(stat->xen_version, "%d.%d%s", major, minor, extra);
snprintf should be used here

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +
if (!domains) || (!domains[first]) || !(domains[first +1]) .... !(domains[first + num])
return -EINVAL

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +		printk("Domain: %d name %s\n", domains[i].id, domains[i].name);
Please use DBG, WARN etc

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	return (domain->state & XEN_DOMINF_running) == XEN_DOMINF_running;
here and in all funcs - add checks for input params

2023-04-07 07:32 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	char path[80];
string line is 20 including \0 + 4 digits of domain_id = 24 should be enough

2023-04-07 07:34 UTC, oleksiimoisieiev requested changes

2023-04-07 07:34 UTC, oleksiimoisieiev commented on xen-shell-cmd/src/xstat_cmds.c
> +#if 0
Probably that should be removed

2023-04-07 07:34 UTC, oleksiimoisieiev commented on xen-shell-cmd/src/xstat_cmds.c
> +#include <string.h>
please run checkpatch

2023-04-07 10:16 UTC, dsemenets commented on Kconfig
> +config XSTAT_SHELL_CMDS
Depends. XSTAT_SHELL_CMDS doesn't compile without XSTAT

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/include/xstat.h
> +#define MAX_DOMAINS 5
Please, use CONFIG_DOM_MAX instead of MAX_DOMAINS and remove this define at all. This will lead to errors even now because these values are different.

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/include/xstat.h
> +#define MAX_VCPUS 8
Unsed define, please, remove it.

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/include/xstat.h
> +#define XENSTAT_ALL (XENSTAT_VCPU|XENSTAT_NETWORK|XENSTAT_XEN_VERSION|XENSTAT_VBD)
From line #73 to here all defines are unused. Please, remove them.

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +	{
Please, move this brace to the line above.

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +	if (num > MAX_DOMAINS)
Please, use CONFIG_DOM_MAX and add braces here.

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +	if (ret < 0)
Please, add braces.

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +	if (ret < 0)
Please, add braces here.

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +unsigned int xenstat_domain_running(xenstat_domain * domain)
Please, remove space before "domain".

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +unsigned int xenstat_domain_blocked(xenstat_domain * domain)
Please, remove space before "domain".

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +unsigned int xenstat_domain_paused(xenstat_domain * domain)
Please, remove space before "domain".

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +unsigned int xenstat_domain_shutdown(xenstat_domain * domain)
Please, remove space before "domain".

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +unsigned int xenstat_domain_crashed(xenstat_domain * domain)
Please, remove space before "domain".

2023-04-07 14:50 UTC, LKomaryanskiy commented on xstat/src/xstat.c
> +unsigned int xenstat_domain_dying(xenstat_domain * domain)
Please, remove space before "domain".

2023-04-10 07:24 UTC, LKomaryanskiy commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	printk("%s for %d\n", __func__, domid);
Please, remove debug code

2023-04-10 07:24 UTC, LKomaryanskiy commented on xstat/include/xstat.h
> +#define MAX_DOM_NAME_SIZE 10
As I see, the same define is in doman.h, which is included here. So this is a redundant definition.

2023-04-10 11:10 UTC, xakep-amatop requested changes

2023-04-10 11:10 UTC, xakep-amatop commented on xstat/include/xstat.h
> +	unsigned long long rbytes;
(question) maybe it will be better to create array of stats for example 0 index for TX and 1 idex for RX

2023-04-10 11:10 UTC, xakep-amatop commented on xstat/src/xstat.c
> +	char path[25];
(cosmetic) magic number

2023-04-10 11:10 UTC, xakep-amatop commented on xstat/src/xstat.c
> +	memset(&info, 0, sizeof(info));
(major) is it what you want to do? here you clear pointer
did you want to do:
`memset(info, 0, sizeof(*info));`
??

2023-04-10 11:22 UTC, xakep-amatop commented on xstat/src/xstat.c
> +	minor = ret & 0xffff;
(question) could you please create named constants for this numbers ?

2023-04-10 11:22 UTC, xakep-amatop commented on xstat/src/xstat.c
> +	stat->cpu_hz = ((unsigned long long)sysctl.u.physinfo.cpu_khz) * 1000ULL;
(note) you don't need both explicit cast to `u64` and `ull` integer-suffix

2023-04-10 11:22 UTC, xakep-amatop commented on xstat/src/xstat.c
> +	stat->tot_mem = ((unsigned long long)sysctl.u.physinfo.total_pages) * CONFIG_MMU_PAGE_SIZE;
(note) brackets are redundant here, the explicit cast operator has higher priority than multiplication

2023-04-10 11:24 UTC, xakep-amatop commented on xstat/src/xstat.c
> +	sysctl.u.getdomaininfolist.buffer.p  = infos;
(note) strange alignment

2023-04-11 06:55 UTC, oleksiimoisieiev requested changes

2023-04-11 06:55 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	if (num > CONFIG_DOM_MAX) {
Empty lines. Please run checkpatch

2023-04-11 06:55 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	domaininfo = sysctl.u.getdomaininfolist.buffer.p;
empty lines

2023-04-11 06:55 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	minor = ret & 0xffff;
Here uint32_t split to 2 uint16_t so I'm not sure about named constants. But I think there should be some existing defines in Zephyr code.

2023-04-11 06:55 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	snprintf(stat->xen_version, VERSION_SIZE, "%d.%d%s", major, minor, extra);
epmty lines. please run checkpatch

2023-04-11 06:55 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	char path[25];
And why it's 25? It's 80 in xenstat.c.

2023-04-11 06:55 UTC, oleksiimoisieiev commented on xen-dom-mgmt/include/domain.h
> +#define MAX_DOM_NAME_SIZE 10
I think this should be configurable on compile time. I don't see such limitation in xen code.

2023-04-11 06:57 UTC, oleksiimoisieiev commented on Kconfig
> +config XSTAT_SHELL_CMDS
I think this should be moved to the commit which is adding shell cmds

2023-04-11 07:02 UTC, oleksiimoisieiev requested changes

2023-04-11 07:02 UTC, oleksiimoisieiev commented on xen-shell-cmd/src/xstat_cmds.c
> +SHELL_CMD_ARG_REGISTER(xstat, &subcmd_xstat, "XStat commands", NULL, 3, 0);
I think there should be 2 mandatory options here - `xstat version` and `xstat top`.

2023-04-11 07:29 UTC, oleksiimoisieiev requested changes

2023-04-11 07:29 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	strncpy(domcfg->name, domain->name, MAX_DOM_NAME_SIZE);
Again and again strncpy do not guaranties string to be null terminated. please use snprintf instead

2023-04-11 07:29 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	memset(&spec, 0, sizeof(spec));
Hm. Why do we need spec to be 0 initialized here? I haven't seen any requirements to parse_json input parameters

2023-04-11 07:29 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +		strncpy(container->vm_name, spec.vm.name, MAX_DOM_NAME_SIZE);
same as above

2023-04-11 07:29 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
> +	JSON_OBJ_DESCR_PRIM(struct vm_spec, name, JSON_TOK_STRING),
Please use "domainname" instead, and please follow the format, described in https://github.com/opencontainers/runtime-spec/blob/main/config.md#platform-specific-configuration

2023-04-11 09:36 UTC, dsemenets commented
> And why it's 25? It's 80 in xenstat.c.
I don't understand. I set 80  you said 20 is enough. I set 25 you say should be 80? What value is correct

2023-04-11 09:42 UTC, oleksiimoisieiev commented on xstat/src/xstat.c
> +	char path[25];
Please ignore my previous comment. I've forgot about the discussion. I think agree with @xakep-amatop that this magic number a bit puzzling. That's why IMHO comment should be added.

2023-04-11 09:43 UTC, oleksiimoisieiev commented
> > And why it's 25? It's 80 in xenstat.c.
> 
> I don't understand. I set 80 you said 20 is enough. I set 25 you say should be 80? What value is correct

Yep. my mistake. I've posted an explanation above

2023-04-11 14:45 UTC, oleksiimoisieiev requested changes

2023-04-11 14:45 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +//	rc = xen_domctl_set_paging_mempool_size(domid, domcfg->max_vcpus * 1024 * 1024 + 8 * domcfg->mem_kb);
please remove this from the commit.

2023-04-12 06:27 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
>  	char container_id[CONTAINER_NAME_SIZE];
Please fix commit message -> /aggress/address also please add more deatiled description

2023-04-12 10:35 UTC, xakep-amatop requested changes

2023-04-12 10:35 UTC, xakep-amatop commented on xstat/src/xstat.c
> +	memset(&info, 0, sizeof(*info));
(major) still not fixed

2023-04-13 05:58 UTC, oleksiimoisieiev commented on xen-shell-cmd/src/xen_cmds.c
> +int dom0_init(const struct shell *shell, size_t argc, char **argv)
You can use SYS_INIT to run init function on startup

2023-04-24 09:15 UTC, closed without merging