Introduce common interface to start the domains
xen-troops/zephyr-xenlib pull request #3
Opened 2023-02-20 15:52 UTC by oleksiimoisieiev

Common interface allows users to start the domains providing domain_config which includes all needed parameters as well as the image and dtb buffers.
Also added calculation of the appropriate dtb address in the Domain ram

2023-02-21 11:49 UTC, firscity requested changes
Also, please make commit message more coherent and consistent.

2023-02-21 11:49 UTC, firscity commented on xen-dom-mgmt/include/xen_dom_mgmt.h
> +int domain_create(const struct shell *shell, struct xen_domain_cfg *domcfg,
Actually shell parameter for functions below is redundant and should be removed. This only required to implement callback for Zephyr shell cmds.

2023-02-21 11:49 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
>  	/*domcfg = (domid == DOMID_DOMD) ? &domd_cfg : &domu_cfg;
This should be removed too.

2023-02-21 11:49 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	if (argc < 3 || argc > 4) {
`argc != 3`?

2023-02-21 11:49 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
>  	if (argc < 3 || argc > 4) {
`argc != 3`

2023-02-21 11:49 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	return domain_create(shell, &domd_cfg, domid);
`&domd_cfg` should be replaced with more generic way, please add TODO here
Not all domains should use this config.

2023-02-22 09:50 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	return domain_create(shell, &domd_cfg, domid);
+

2023-02-22 09:50 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	if (argc < 3 || argc > 4) {
+

2023-02-22 09:50 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
>  	if (argc < 3 || argc > 4) {
+

2023-02-22 09:50 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
>  	/*domcfg = (domid == DOMID_DOMD) ? &domd_cfg : &domu_cfg;
+

2023-02-22 09:50 UTC, oleksiimoisieiev commented on xen-dom-mgmt/include/xen_dom_mgmt.h
> +int domain_create(const struct shell *shell, struct xen_domain_cfg *domcfg,
+

2023-02-22 14:56 UTC, firscity approved these changes
`Reviewed-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2023-02-23 09:08 UTC, merged