xen-dom-mgmt: Create partial device tree for domain
xen-troops/zephyr-xenlib pull request #4
Opened 2023-02-23 09:56 UTC by oleksiimoisieiev

Add external library libfdt to the project to add the device tree support. This is required to create partial device-tree for the domains.
Partial device-tree generates all basic nodes for the Guest Domain and supports GICv2/GiCv3 switch and optee as optionally. Current implementation doesn't support providing HW configuration in the Domain DT.

Zephyr should be configured with the following param: CONFIG_MINIMAL_LIBC_MALLOC_ARENA_SIZE=8192
to have enough heap size to store created DT.

Libfdt details:

Expected location: <zephyr-xenlib path>/../dtc
Repo: https://kernel.googlesource.com/pub/scm/utils/dtc/dtc
Tag: v1.7.0

2023-02-23 20:37 UTC, lorc requested changes

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +typedef uint32_t be32;
Bold of you to assume that ARM64 always works in Big-Endian mode... You need to hide this typedef under `#ifdef CONFIG_BIG_ENDIAN` at least.

Even better to use zephyr/include/zephyr/sys/byteorder.h

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	p = compat = malloc(sz);
`malloc` can return `NULL`

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	return fdt_property(fdt, "compatible", compat, sz);
Who now owns `compat`? Where it will be freed?

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/include/xen-dom-fdt.h
> +						   size_t *fdtsize, int xen_major, int xen_minor,
There is something strange with formatting in the whole patch. Could you please review it?
Looks like your tab length is 4

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +		memset(name, 0, size); \
Why do you need to zero-out buffer every time?

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	printk("/chosen/bootargs = %s", cmdline);
Is this for debug?

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +    res = fdt_property_compat(fdt, 2, name, "xen,xen");
strange formatting

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +    int r;
This function has totally different indentation.

Seriously, check your diffs before posting.

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +static int check_partial_fdt(void *fdt, size_t size)
I am having slight deja vu... 

This code is copied from xen/tools/libs/light/libxl_arm.c, isn't it? What about licensing issues?

2023-02-23 20:37 UTC, lorc commented on xen-dom-mgmt/include/xen-dom-fdt.h
> +int gen_domain_partial_fdt(struct xen_domain_cfg *domcfg, void **fdtaddr,
Why this is "partial", BTW? For me it looks like complete device tree.

FYI, "Partial" device is an additional device tree blob, that libxl use to generate full device tree.

2023-03-01 18:02 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	return fdt_property(fdt, "compatible", compat, sz);
+

2023-03-01 18:02 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	p = compat = malloc(sz);
+

2023-03-01 18:04 UTC, oleksiimoisieiev commented on xen-dom-mgmt/include/xen-dom-fdt.h
> +						   size_t *fdtsize, int xen_major, int xen_minor,
+

2023-03-01 18:07 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +		memset(name, 0, size); \
yes. It seems like fdt_property doesn't handle strings correctly. I've got garbage in names before memset. I may be wrong.

2023-03-01 18:08 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	printk("/chosen/bootargs = %s", cmdline);
Yes. I intend to make it LOG_DBG when Dima will refacror logging in xenlib.

2023-03-01 18:12 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +static int check_partial_fdt(void *fdt, size_t size)
I thought all xen-dom-mgmt was partly copied from libxl.arm. I've renamed function.

2023-03-01 18:13 UTC, oleksiimoisieiev commented on xen-dom-mgmt/include/xen-dom-fdt.h
> +int gen_domain_partial_fdt(struct xen_domain_cfg *domcfg, void **fdtaddr,
fixed

2023-03-02 01:05 UTC, lorc commented on CMakeLists.txt
> +add_subdirectory_ifdef(CONFIG_LIBFDT libfdt)
I'd name this config more local-scoped. Something like `CONFIG_XENLIB_LIBFDT`. Just in case if Zephyr project would add own `LIBFDT` support

2023-03-02 01:05 UTC, lorc commented on Kconfig
> -	select LIBFDT
Why did you enforced LIBFDT in the previous commit if you are removing it now?

2023-03-02 01:05 UTC, lorc commented on xen-dom-mgmt/CMakeLists.txt
> +add_library(XENDOM_MGMT STATIC IMPORTED GLOBAL)
This is not covered in the commit message. Do you really need this?

2023-03-02 01:05 UTC, lorc commented on xen-dom-mgmt/CMakeLists.txt
> +ExternalProject_Add(
Why do you need all of this?

2023-03-02 01:05 UTC, lorc commented on xen-dom-mgmt/include/domain.h
> +	char *cmdline;
Should this belong to this commit?

2023-03-02 09:18 UTC, oleksiimoisieiev commented on Kconfig
> -	select LIBFDT
fixed

2023-03-02 09:18 UTC, oleksiimoisieiev commented on xen-dom-mgmt/CMakeLists.txt
> +add_library(XENDOM_MGMT STATIC IMPORTED GLOBAL)
Fixed

2023-03-02 09:18 UTC, oleksiimoisieiev commented on xen-dom-mgmt/CMakeLists.txt
> +ExternalProject_Add(
Removed

2023-03-02 09:18 UTC, oleksiimoisieiev commented on xen-dom-mgmt/include/domain.h
> +	char *cmdline;
Moved to separate commit

2023-03-02 09:19 UTC, oleksiimoisieiev commented on CMakeLists.txt
> +add_subdirectory_ifdef(CONFIG_LIBFDT libfdt)
Changing it to XEN_LIBFDT similar to other modules in xenlib

2023-03-02 16:03 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +typedef uint32_t be32;
Removed this typedef. Looks like zephyr doesn't use be32 type. so according to the similar code in zimage.h I've just put uint32_t instead

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +								   unsigned num_irq)
Something strange with formatting there.

May I ask you to try to integrate `checkpatch` into this project?

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	if (res) return res;
Coding style is inconsistent in the whole file.

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	uint32_t *cells = &regs[0];
That's... funny way to write `uint32_t *cells = regs`. Or am I missing something there?

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	printk("bootargs = %s", cmdline);
Isn't there a new logging API in the Zephyr?

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	res = fdt_property_string(fdt, "bootargs", cmdline);
Missing check on `res`

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +		if (size_left == 0)
You can just put this into the `for` loop: `for (i = 0; i < GUEST_RAM_BANKS && size_left; i++)`.

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	  return res;
You really need some style checker. Or just press `C-x h TAB` in Emacs :)

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +						  unsigned int cpumask, unsigned int level) {
Newer saw coding style standard that allows `{` in the same line for function definition.

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +#define HYPERVISOR_REG0_BASE 0x38000000
Could you please move this into top of the file? Also either add comments that describe what every register mean, or give them better names

2023-03-02 22:43 UTC, lorc commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +#define CHECK_FDT_RES(rc) do { \
Might as well move this macro on top of the file and you in all functions.

2023-03-03 13:58 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +								   unsigned num_irq)
+

2023-03-03 13:59 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	if (res) return res;
+

2023-03-03 14:05 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	uint32_t *cells = &regs[0];
+

2023-03-03 14:06 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	printk("bootargs = %s", cmdline);
Stil using printk. waiting for Dima to integrate LOG_* across the project.

2023-03-03 14:07 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	res = fdt_property_string(fdt, "bootargs", cmdline);
+

2023-03-03 14:08 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +		if (size_left == 0)
+

2023-03-03 14:09 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +						  unsigned int cpumask, unsigned int level) {
this damn emacs doing this on each paste (((. Fixed

2023-03-06 11:27 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +#define HYPERVISOR_REG0_BASE 0x38000000
Fixed

2023-03-07 09:33 UTC, firscity reviewed
Also `Create domain device tree for domain` sounds strange, I think it is better to reword it (remove tautology)

`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2023-03-07 09:33 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-fdt.c
> +	res = fdt_property_compat(fdt, 2,
Something wrong with formatting here

2023-03-07 10:06 UTC, oleksiimoisieiev commented
Updated comment and added Ack

2023-03-07 12:55 UTC, lorc commented
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2023-03-07 13:57 UTC, merged