xen-dom-mgmt: domU isn't ab;e to load without passthrough node
xen-troops/zephyr-xenlib pull request #52
Opened 2024-02-19 09:46 UTC by xakep-amatop

Some of DomU may have empty or deleted passthrough node, but 'copy_node_by_path' doesn't handle it.

2024-02-19 18:43 UTC, lorc requested changes
I am fine with the diff. But please, align the commit message with the standard. 

https://www.kernel.org/doc/html/latest/process/submitting-patches.html#describe-your-changes

Pay attention to the "imperative mood" part.

2024-03-14 07:19 UTC, xakep-amatop commented
> I am fine with the diff. But please, align the commit message with the standard.
> 
> https://www.kernel.org/doc/html/latest/process/submitting-patches.html#describe-your-changes
> 
> Pay attention to the "imperative mood" part.

done

2024-03-16 11:11 UTC, firscity approved these changes
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2024-03-16 20:12 UTC, xakep-amatop commented
added ack

2024-03-18 10:23 UTC, firscity commented
@lorc, can you please re-check a new commit message?

2024-03-18 17:46 UTC, lorc approved these changes
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2024-03-19 07:31 UTC, xakep-amatop commented
added ack

2024-03-19 09:55 UTC, merged