xen-dom-mgmt: Add uImage loader support to boot uImages
xen-troops/zephyr-xenlib pull request #6
Opened 2023-02-27 14:06 UTC by oleksiimoisieiev

uImage loader parses uimage_header which includes data about
image loading addresses. This is useful for the images which has
precompiled load_address.
For example: if Domain image is precompiled to boot from address
0x40080000, it can be converted to uImage using the following command:

mkimage -A arm64 -O linux -T kernel -C none -a 0x40080000 -e 0x40080000 -n "kernel" -d Image uImage

Generated uImage can be used as the Domain.

Signed-off-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>

2023-02-27 14:16 UTC, lorc reviewed
Couple of questions: 

There are multiple image formats: U-Boot uImage, ELF image, UEFI/MS PE image, linux Image. Most of them either define load address or provide some hints about where image should be placed. All of them provide entry point address. Maybe we just support some of this image formats? Like xen tools do.

Another question is regarding patch itself. I see no connection between "load address offset", "exact" and "entry point". For instance:

 - load address and entry point address are not the same
 - relative offset can't define "exact" address

2023-03-01 10:53 UTC, firscity requested changes

2023-03-01 10:53 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +#include <zephyr/xen/dom0/uimage.h>
I don't see this header added to Zephyr in any other PR.

2023-03-01 10:53 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	struct modules_address modules;
It is better to initialize it with `{0}`, because I see the NULL check bellow. Functions, that initializes this may return earlier.

2023-03-01 10:53 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +		base_addr > GUEST_RAM0_BASE + GUEST_RAM0_SIZE)
GUEST_RAM0_SIZE should not be used here. It is only use to limit RAM0 bank, not for searching end of domain RAM. You should use `domcfg->memkb`.

2023-03-01 10:53 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	if (base_addr + len > GUEST_RAM0_BASE + GUEST_RAM0_SIZE)
Same issue with GUEST_RAM0_SIZE

2023-03-01 10:53 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +uint64_t probe_uimage(int domid, struct xen_domain_cfg *domcfg,
Function is `uint64_t`, but you are returning negative error codes. Please, fix it.

2023-03-01 10:53 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +		rc = xendom_remove_from_physmap(DOMID_SELF, mapped_pfns[i]);
Here is legacy issue with void in this function. Please handle the `rc` if you are reusing this code.

2023-03-01 10:53 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	mapped_dtb = k_aligned_alloc(XEN_PAGE_SIZE, XEN_PAGE_SIZE * nr_pages);
Here should be a NULL check after allocation

2023-03-01 10:53 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	printk("U-Boot dtb start addr = %p, end addr = %p, binary size = 0x%llx\n", dtb_start,
This comments probably should be removed or changed.

2023-03-01 10:53 UTC, firscity commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	mapped_dtb_pfn = XEN_PHYS_PFN((uint64_t)mapped_dtb);
Please change casting with `xen_virt_to_gfn()`, it is also a legacy problem.

2023-03-02 10:34 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	struct modules_address modules;
+

2023-03-02 10:41 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +		base_addr > GUEST_RAM0_BASE + GUEST_RAM0_SIZE)
+

2023-03-02 10:41 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	if (base_addr + len > GUEST_RAM0_BASE + GUEST_RAM0_SIZE)
+

2023-03-02 10:42 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +uint64_t probe_uimage(int domid, struct xen_domain_cfg *domcfg,
+

2023-03-02 12:07 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +		rc = xendom_remove_from_physmap(DOMID_SELF, mapped_pfns[i]);
+

2023-03-02 12:10 UTC, oleksiimoisieiev commented on xen-dom-mgmt/src/xen-dom-mgmt.c
> +	mapped_dtb_pfn = XEN_PHYS_PFN((uint64_t)mapped_dtb);
+

2023-03-02 12:10 UTC, oleksiimoisieiev commented
Updated. @firscity  please take a look

2023-03-02 12:39 UTC, firscity approved these changes
Good job, thank you!
`Reviewed-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2023-03-02 13:05 UTC, merged