xrun: Add reference counting to container objects
xen-troops/zephyr-xenlib pull request #67
Opened 2024-04-16 07:29 UTC by Deedone

Add reference counting to container objects to prevent unexpected failures when container object is freed right after return from get_container function.

2024-04-16 17:14 UTC, lorc commented on xrun/src/xrun.c
> +	container = find_container_locked(container_id);
This is prone to ABA problem. Reference owner should hold own pointer to the container.

2024-04-16 17:14 UTC, lorc commented on xrun/src/xrun.c
>  	ret = domain_pause(container->domid);
Here is another issue, which is related: all this pause/unpause stuff should be done while holding container own lock.

We need another patch to fix this.

2024-04-16 17:14 UTC, lorc commented on xrun/src/xrun.c
>  	return unregister_container_id(container_id);
You can just call `put_container` for a second time here. With a comment, of course.

2024-04-17 07:46 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
>  	ret = domain_pause(container->domid);
I support domain_pause/unpause is responsible for this lock. Because to be honest this lock should be domid own lock rather then container related.

2024-04-17 07:50 UTC, oleksiimoisieiev requested changes

2024-04-17 07:50 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
>  }
```suggestion
	ret = domain_unpause(container->domid);
	if (ret) {
		goto out;
	}

	container->status = RUNNING;
out:
	put_container(container);
	return ret;
}
```

2024-04-17 07:50 UTC, oleksiimoisieiev commented on xrun/src/xrun.c
>  }
Not mandatory. Just will look more readable from my standpoint. The same suggestion across all put_container calls

2024-04-17 10:52 UTC, Deedone commented on xrun/src/xrun.c
>  	ret = domain_pause(container->domid);
Is it not ok? We can be sure that the container pointer is valid, and if two different threads try to write to `container->status` at the same time, one of those writes would be overwritten by the other in any case.

2024-04-17 10:58 UTC, lorc commented on xrun/src/xrun.c
>  	ret = domain_pause(container->domid);
```
    Thread-1   |   Thread-2
               |
domain_pause() |
               |
           CTX SWITCH
               |
               | domain_unpause()
               | state = unpaused
               |
           CTX SWITCH
               |
state = paused |
               |
```

2024-04-22 16:02 UTC, GrygiriiS commented
Similar comment as https://github.com/xen-troops/zephyr-xenlib/pull/72#issuecomment-2069257869

2024-08-01 23:08 UTC, lorc commented on xrun/src/xrun.c
> -	 */
It is a pity, but this function has another concurrency issue: code below checks if container exists by using `get_container`. Problem is that if `register_container_id` is called twice with the same container id, it may register both containers. You need to hold the container lock whole time: obtain the lock, check if container already exists, create new one, free the lock.

This is another issue, so you can add TODO for now. Or make a separate patch that fixes this.

2024-08-01 23:08 UTC, lorc commented on xrun/src/xrun.c
> +	put_container(container);
Hm... should you call `domain_destroy` when you are freeing container? Or it will be okay to have a container object without alive domain inside?

2024-08-02 10:49 UTC, lorc reviewed
That should to. Thanks.

How you tested this, BTW?

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2024-08-02 10:57 UTC, lorc commented
Oh, and  don't forget to fix checkpatch.

2024-08-03 07:57 UTC, Deedone commented
Tested with unit tests and trying to start/stop/pause/unpause the aos monkey container.

2024-08-05 16:18 UTC, firscity approved these changes
Thank you
`Reviewed-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2024-08-12 10:36 UTC, merged