xen-shell-cmd: ensure shell cmds do not change domain cfg
xen-troops/zephyr-xenlib pull request #92
Opened 2024-06-14 13:30 UTC by GrygiriiS

The commit 7c39b5623258 ("xen-shell-cmd: add optional parameter for pausing domain on creation") and commit e528793c3ccc ("xen-dom-mgmt: add option to read domain partial device-tree") added new functionality to the xenlib shell command interface, but at the same time those commits change some fields in struct xen_domain_cfg object while executing the "xu create" command. This leads to unexpected behavior, like for the first commit:

 domcfg->f_paused = false
 xu create rpi_5_domu    --> unpaused
 xu create rpi_5_domu -p --> paused cfg->f_paused=true
 xu create rpi_5_domu    --> paused cfg->f_paused=true
 xu create rpi_5_domu -p --> paused cfg->f_paused=true
 xu create rpi_5_domu    --> paused cfg->f_paused=true

so once domain is creted with "-p" option - it will be always created in "paused" state after this.

For the second commit situation is similar, partial DT will be red from storage only once.

Hence shell interface allows to execute only one command at time the above issues are fixed by saving and restoring modified fields of struct xen_domain_cfg.

2024-06-14 14:55 UTC, lorc reviewed
Okay, I see the issue and I agree that shell should not change domain config.

But I am confused a bit  by the solution. IMO, it adds unnecessary complexity. Maybe it would be simpler to create copy of `domain_cfg` and use it? This will ensure that any similar issues will be covered as well.

2024-06-14 14:55 UTC, lorc commented on xen-shell-cmd/src/xen_cmds.c
> +struct xen_shell_dom_mgmt_context shell_dom_mgmt_ctx;
`static`

2024-06-14 15:04 UTC, GrygiriiS commented
> Okay, I see the issue and I agree that shell should not change domain config.
> 
> But I am confused a bit by the solution. IMO, it adds unnecessary complexity. Maybe it would be simpler to create copy of `domain_cfg` and use it? This will ensure that any similar issues will be covered as well.

I'll think about and try it. Thanks.

2024-06-18 09:31 UTC, firscity requested changes

2024-06-18 09:31 UTC, firscity commented on xen-shell-cmd/src/xen_cmds.c
> +	domcfg_tmp = *cfg;
This part (`domain_create()`) can be called from multiple places, so `domcfg_tmp` may be over-written. You need to use either locks, or complete independent copy of the config.

2024-06-18 09:31 UTC, firscity commented on xen-shell-cmd/src/xen_cmds.c
> +	*cfg = domcfg_tmp;
Are you sure that every provider of `domain_find_config()` will be happy with this? The best way will be using a complete copy and don't touch original config at all

2024-06-19 09:58 UTC, firscity approved these changes
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

2024-06-25 11:03 UTC, firscity commented
@lorc can you please re-check?

2024-06-26 16:36 UTC, lorc approved these changes
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2024-07-01 15:39 UTC, merged